name: Run Tests

on:
    workflow_dispatch:

    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    run-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up node
              uses: actions/setup-node@v4
              with:
                node-version: lts/*
            
            - name: Install dependencies
              run:  yarn install

            - name: Build
              run: yarn build

            - name: Install Playwright & Browsers
              run: npx playwright install --with-deps

            - name: Start solo
              run: make solo-up

            - name: Launch test app
              run: cd apps/test-app && yarn dev &

            - name: Run tests
              id: run-tests
              run: yarn test

            - name: Upload test results
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: playwright-results
                path: ./tests/playwright/playwright-report
                retention-days: 5